default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'root' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>


development:
  <<: *default
  database: coocre_development

test:
  <<: *default
  database: coocre_test

production:
  <<: *default
  database: coocre_production
  username: coocre
  password: <%= ENV['COOCRE_DATABASE_PASSWORD'] %>
